"""Regenerates src/population_tracker/tables.py from the Chaos.Cryptography C# source.

The salt and CRC tables are protocol constants. Rather than transcribing them by
hand, parse them out of Tables.cs so they can be re-derived if Chaos ever changes.

Usage:
    py tools/generate_tables.py [path/to/Chaos-Server/Chaos.Cryptography/Tables.cs]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DEFAULT_SOURCE = Path(__file__).resolve().parents[2] / "Chaos-Server" / "Chaos.Cryptography" / "Tables.cs"
OUTPUT = Path(__file__).resolve().parents[1] / "src" / "population_tracker" / "tables.py"


def parse_numbers(block: str) -> list[int]:
    return [int(n) for n in re.findall(r"-?\d+", block)]


def extract_array(source: str, name: str) -> str:
    """Returns the text between `name = new ...[]{` and the matching `}`."""
    start = source.index(name)
    open_brace = source.index("{", start)
    depth = 0

    for i in range(open_brace, len(source)):
        if source[i] == "{":
            depth += 1
        elif source[i] == "}":
            depth -= 1

            if depth == 0:
                return source[open_brace + 1 : i]

    raise ValueError(f"unterminated array for {name}")


def main() -> int:
    src_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SOURCE

    if not src_path.is_file():
        print(f"Tables.cs not found at {src_path}", file=sys.stderr)
        return 1

    source = src_path.read_text(encoding="utf-8")

    table16 = parse_numbers(extract_array(source, "TABLE16"))

    salt_block = extract_array(source, "SALT_TABLE")
    salt_table = [parse_numbers(inner) for inner in re.findall(r"new byte\[\]\s*\{([^}]*)\}", salt_block)]

    if len(table16) != 256:
        raise ValueError(f"TABLE16 has {len(table16)} entries, expected 256")

    if len(salt_table) != 10 or any(len(salts) != 256 for salts in salt_table):
        raise ValueError("SALT_TABLE must be 10 tables of 256 bytes")

    lines = [
        '"""Protocol constant tables. Generated by tools/generate_tables.py - do not edit."""',
        "",
        "from typing import Final",
        "",
        "#: CRC-16/CCITT-FALSE lookup table (polynomial 0x1021).",
        "CRC16_TABLE: Final[tuple[int, ...]] = (",
    ]
    lines += [f"    {', '.join(str(n) for n in table16[i : i + 12])}," for i in range(0, 256, 12)]
    lines += [
        ")",
        "",
        "#: One 256-byte salt table per encryption seed (0-9).",
        "SALT_TABLE: Final[tuple[bytes, ...]] = (",
    ]

    for salts in salt_table:
        lines.append(f"    bytes({salts!r}),")

    lines += [")", ""]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(salt_table)} salt tables, {len(table16)} crc entries)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
